language: python
sudo: false
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
env:
- REQ="Django>=1.8,<1.9"
- REQ="Django>=1.9,<1.10"
- REQ="Django>=1.10,<1.11"
- REQ="Django>=1.11,<2.0"
- REQ="Django>=2.0,<2.1"
matrix:
  exclude:
  - python: 2.7
    env: REQ="Django>=2.0,<2.1"
services:
- postgresql
install:
- pip install -U pip wheel
- pip install $REQ psycopg2 pytz
script: PYTHONWARNINGS=all PYTHONPATH=. ./cte_tree_test/manage.py test
